@extends('layouts.guest')

@section('title', 'Accueil')

@section('styles')
 <link rel="stylesheet" href="{{ asset('css/Home.css') }}">
@endsection

@section('content')

<div style="text-align: right; padding: 15px 30px;">
    @auth
        <a href="{{ route('admin.dashboard') }}" style="margin-right: 15px;">
            Dashboard
        </a>

        <form method="POST" action="{{ route('logout') }}" style="display:inline;">
            @csrf
            <button type="submit">Logout</button>
        </form>
    @else
        <a href="{{ route('login') }}">Connexion</a>
    @endauth
</div>
<!-- Hero Section -->
<section class="hero" id="home">
    <div class="container">
        <h2>Gestion centralisée des ressources informatiques</h2>
        <p>Optimisez l'utilisation de vos serveurs, machines virtuelles, stockage et équipements réseau avec notre plateforme de réservation et de suivi en temps réel.</p>
        <div class="cta-buttons">
            <button class="btn-primary hover-lift" id="explore-resources">Explorer les ressources</button>
            <button class="btn-secondary hover-lift" id="learn-more">En savoir plus</button>
        </div>
    </div>
</section>

<!-- Resources Section -->
<section class="resources-section" id="resources">
    <div class="container">
        <div class="section-title">
            <h2>Ressources disponibles</h2>
            <p>Parcourez les ressources informatiques du data center. Connectez-vous pour voir les détails complets et faire des réservations.</p>
        </div>
        <div class="resources-container" id="resources-container">
            <!-- Resources will be generated by JavaScript -->
        </div>
    </div>
</section>

<!-- Rules Section -->
<section class="rules-section" id="rules">
    <div class="container">
        <div class="section-title">
            <h2>Règles d'utilisation des ressources</h2>
            <p>Politiques et directives pour garantir une exploitation optimale et équitable</p>
        </div>
        <div class="rules-container">
            <div class="rules-grid">
                <div class="rule-card gradient-border">
                    <h4><i class="fas fa-calendar-check"></i> Réservations</h4>
                    <p>Les réservations doivent être effectuées au minimum 24 heures à l'avance. Durée maximale : 30 jours consécutifs.</p>
                </div>
                <div class="rule-card gradient-border">
                    <h4><i class="fas fa-exclamation-triangle"></i> Utilisation responsable</h4>
                    <p>Les ressources doivent être utilisées exclusivement pour des projets académiques ou de recherche.</p>
                </div>
                <div class="rule-card gradient-border">
                    <h4><i class="fas fa-chart-bar"></i> Monitoring</h4>
                    <p>L'utilisation des ressources est monitorée. Un rapport d'utilisation doit être fourni à la fin de chaque projet.</p>
                </div>
                <div class="rule-card gradient-border">
                    <h4><i class="fas fa-tools"></i> Maintenance</h4>
                    <p>Maintenance planifiée le premier weekend de chaque mois. Notification 7 jours à l'avance.</p>
                </div>
                <div class="rule-card gradient-border">
                    <h4><i class="fas fa-shield-alt"></i> Sécurité</h4>
                    <p>Respect des politiques de sécurité obligatoire. Données sensibles chiffrées et accès protégés.</p>
                </div>
                <div class="rule-card gradient-border">
                    <h4><i class="fas fa-ban"></i> Restrictions</h4>
                    <p>Interdit : minage de cryptomonnaies, contenus illégaux, activités compromettant la sécurité.</p>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@section('scripts')
<script>
    // Données des ressources
    const resources = [
        {
            id: 1,
            title: "Serveur HP ProLiant DL380",
            type: "Serveur physique",
            description: "Serveur haute performance pour applications critiques et virtualisation intensive.",
            image: "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=400",
            status: "available"
        },
        {
            id: 2,
            title: "VM VMware vSphere",
            type: "Machine virtuelle",
            description: "Environnement virtualisé avec ressources dédiées pour développement et tests.",
            image: "https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=400",
            status: "available"
        },
        {
            id: 3,
            title: "Baie de stockage Dell EMC",
            type: "Stockage",
            description: "Solution de stockage SAN haute capacité avec réplication de données.",
            image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=400",
            status: "maintenance"
        },
        {
            id: 4,
            title: "Commutateur Cisco Nexus",
            type: "Réseau",
            description: "Équipement réseau haute performance pour connectivité avancée.",
            image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400",
            status: "available"
        },
        {
            id: 5,
            title: "Serveur GPU NVIDIA DGX",
            type: "Serveur IA",
            description: "Infrastructure dédiée au calcul intensif et apprentissage automatique.",
            image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400",
            status: "unavailable"
        },
        {
            id: 6,
            title: "Cluster Kubernetes",
            type: "Conteneurs",
            description: "Environnement conteneurisé pour déploiement et orchestration modernes.",
            image: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400",
            status: "available"
        }
    ];

    // Éléments DOM
    const loginBtn = document.getElementById('login-btn');
    const loginModal = document.getElementById('login-modal');
    const closeModal = document.getElementById('close-modal');
    const loginForm = document.getElementById('login-form');
    const registerForm = document.getElementById('register-form');
    const showRegister = document.getElementById('show-register');
    const showLogin = document.getElementById('show-login');
    const modalTitle = document.getElementById('modal-title');
    const exploreResourcesBtn = document.getElementById('explore-resources');
    const resourcesContainer = document.getElementById('resources-container');

    // Générer les cartes de ressources
    function generateResourceCards() {
        resourcesContainer.innerHTML = '';
        
        resources.forEach(resource => {
            const card = document.createElement('div');
            card.className = 'resource-card gradient-border';
            
            let statusClass = '';
            let statusText = '';
            if (resource.status === 'available') {
                statusText = 'Disponible';
            } else if (resource.status === 'unavailable') {
                statusClass = 'unavailable';
                statusText = 'Indisponible';
            } else if (resource.status === 'maintenance') {
                statusClass = 'maintenance';
                statusText = 'Maintenance';
            }
            
            card.innerHTML = `
                <div class="resource-image">
                    <img src="${resource.image}" alt="${resource.title}">
                </div>
                <div class="resource-content">
                    <span class="resource-type">${resource.type}</span>
                    <h3 class="resource-title">${resource.title}</h3>
                    <p class="resource-desc">${resource.description}</p>
                    <div class="resource-details">
                        <div class="resource-status">
                            <span class="status-dot ${statusClass}"></span>
                            <span>${statusText}</span>
                        </div>
                        <div class="resource-action">
                            <i class="fas fa-chevron-right"></i>
                        </div>
                    </div>
                    <div class="login-required">
                        <i class="fas fa-lock"></i> Connectez-vous pour voir les détails complets
                    </div>
                </div>
            `;
            
            card.addEventListener('click', () => {
                loginModal.style.display = 'flex';
                card.style.transform = 'scale(0.98)';
                setTimeout(() => {
                    card.style.transform = '';
                }, 200);
            });
            
            resourcesContainer.appendChild(card);
        });
    }

    // Afficher/masquer modal de connexion
    loginBtn.addEventListener('click', () => {
        loginModal.style.display = 'flex';
        loginBtn.style.transform = 'scale(0.95)';
        setTimeout(() => {
            loginBtn.style.transform = '';
        }, 200);
    });

    closeModal.addEventListener('click', () => {
        loginModal.style.display = 'none';
    });

    window.addEventListener('click', (e) => {
        if (e.target === loginModal) {
            loginModal.style.display = 'none';
        }
    });

    // Basculer entre login et register
    showRegister.addEventListener('click', (e) => {
        e.preventDefault();
        loginForm.style.display = 'none';
        registerForm.style.display = 'block';
        modalTitle.textContent = 'Créer un compte';
    });

    showLogin.addEventListener('click', (e) => {
        e.preventDefault();
        registerForm.style.display = 'none';
        loginForm.style.display = 'block';
        modalTitle.textContent = 'Connexion';
    });

    // Gérer la soumission du formulaire de connexion
    loginForm.addEventListener('submit', (e) => {
        e.preventDefault();
        const email = document.getElementById('email').value;
        
        alert(`Connexion réussie !\nEmail: ${email}\n\n(Simulation - Intégration Laravel à venir)`);
        loginModal.style.display = 'none';
        loginForm.reset();
    });

    // Gérer la soumission du formulaire d'inscription
    registerForm.addEventListener('submit', (e) => {
        e.preventDefault();
        const name = document.getElementById('name').value;
        const email = document.getElementById('email-register').value;
        
        alert(`Demande de compte envoyée !\nNom: ${name}\nEmail: ${email}\n\nVotre demande sera traitée par un administrateur.\n(Simulation - Intégration Laravel à venir)`);
        registerForm.style.display = 'none';
        loginForm.style.display = 'block';
        modalTitle.textContent = 'Connexion';
        registerForm.reset();
    });

    // Bouton explorer les ressources
    exploreResourcesBtn.addEventListener('click', () => {
        document.getElementById('resources').scrollIntoView({ 
            behavior: 'smooth',
            block: 'start'
        });
        exploreResourcesBtn.style.transform = 'scale(0.95)';
        setTimeout(() => {
            exploreResourcesBtn.style.transform = '';
        }, 200);
    });

    // Bouton "En savoir plus"
    document.getElementById('learn-more').addEventListener('click', () => {
        alert("DATA CENTER RESOURCE MANAGEMENT\n\n✓ Gestion complète des ressources informatiques\n✓ Système de réservation avec validation\n✓ Notifications automatiques\n✓ Tableaux de bord statistiques\n✓ Interface sécurisée\n\nTechnologies: Laravel, MySQL, HTML/CSS/JavaScript\n\nThème: Palette claire et moderne\n\nNOTE: Les comptes technicien et administrateur existent déjà - création de compte uniquement pour utilisateurs internes");
    });

    // Effets de survol améliorés
    document.addEventListener('DOMContentLoaded', () => {
        generateResourceCards();
        
        // Ajout d'effets de survol aux cartes
        const cards = document.querySelectorAll('.resource-card, .rule-card');
        cards.forEach(card => {
            card.addEventListener('mouseenter', function() {
                this.style.boxShadow = '0 15px 35px rgba(46, 204, 113, 0.15)';
            });
            
            card.addEventListener('mouseleave', function() {
                this.style.boxShadow = '';
            });
        });

        // Effet de particules subtil
        createParticles();
    });

    // Création de particules subtiles
    function createParticles() {
        const particlesContainer = document.createElement('div');
        particlesContainer.className = 'particles';
        document.body.appendChild(particlesContainer);
        
        for (let i = 0; i < 20; i++) {
            const particle = document.createElement('div');
            particle.className = 'particle';
            particle.style.left = `${Math.random() * 100}%`;
            particle.style.animationDelay = `${Math.random() * 5}s`;
            particle.style.animationDuration = `${5 + Math.random() * 10}s`;
            particlesContainer.appendChild(particle);
        }
    }

    // Effet de souris qui suit
    document.addEventListener('mousemove', (e) => {
        const cards = document.querySelectorAll('.hover-lift');
        cards.forEach(card => {
            const rect = card.getBoundingClientRect();
            const x = e.clientX - rect.left;
            const y = e.clientY - rect.top;
            
            if (x > 0 && x < rect.width && y > 0 && y < rect.height) {
                const centerX = rect.width / 2;
                const centerY = rect.height / 2;
                
                const rotateY = ((x - centerX) / centerX) * 2;
                const rotateX = ((centerY - y) / centerY) * 2;
                
                card.style.transform = `perspective(1000px) rotateX(${rotateX}deg) rotateY(${rotateY}deg) translateZ(10px)`;
            } else {
                card.style.transform = '';
            }
        });
    });
</script>
@endsection